=== oggg/TelerikAcademy/DB/01. XML Basics/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           targetNamespace="urn:students" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="email">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="gender" type="xs:string" />
              <xs:element name="birth_date" type="xs:string" />
              <xs:element name="phone" type="xs:long" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="course" type="xs:unsignedByte" />
              <xs:element name="speciality" type="xs:string" />
              <xs:element name="faculcy_number" type="xs:unsignedInt" />
              <xs:element name="exams_passed">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="exam">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="exam_title" type="xs:string" />
                          <xs:element name="tutor" type="xs:string" />
                          <xs:element name="score" type="xs:unsignedByte" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="enrollment-info">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enrollment-date" type="xs:date" />
                    <xs:element name="exam-score" type="xs:decimal" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="teacher-endorsments">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="teacher-name" type="xs:string" />
                    <xs:element name="teacher-endorsement" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== oggg/TelerikAcademy/DB/01. XML Basics/students.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students xmlns="urn:students"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="students file://./students.xsd">
  <student>
    <name>Pesho</name>
    <gender>male</gender>
    <birth_date>01.01.1990</birth_date>
    <phone>+359888888888</phone>
    <email>Pesho@mail.com</email>
    <course>2</course>
    <speciality>Programing</speciality>
    <faculcy_number>123456</faculcy_number>
    <exams_passed>
      <exam>
        <exam_title>C#1</exam_title>
        <tutor>Ivo</tutor>
        <score>90</score>
      </exam>
      <exam>  
        <exam_title>C#2</exam_title>
        <tutor>Ivo</tutor>
        <score>100</score>
      </exam>
    </exams_passed>
  </student>
  <student>
    <name>Gosho</name>
    <gender>male</gender>
    <birth_date>01.01.1991</birth_date>
    <phone>+359888888889</phone>
    <email>Gosho@mail.com</email>
    <course>2</course>
    <speciality>Programing</speciality>
    <faculcy_number>123455</faculcy_number>
    <exams_passed>
      <exam>
        <exam_title>Js fundamentals</exam_title>
        <tutor>Evlogi</tutor>
        <score>90</score>
      </exam>
      <exam>
        <exam_title>Js OOP</exam_title>
        <tutor>Doncho</tutor>
        <score>100</score>
      </exam>
    </exams_passed>
  </student>
</students>
